import { ADMIN_ROLES, PERMISSION_RESOURCES, PERMISSION_ACTIONS } from './constants';

// Full Permission Matrix (from your spec)
const PERMISSION_MATRIX = {
  [ADMIN_ROLES.SUPER_ADMIN]: {
    [PERMISSION_RESOURCES.USERS]: [
      PERMISSION_ACTIONS.VIEW,
      PERMISSION_ACTIONS.CREATE,
      PERMISSION_ACTIONS.UPDATE,
      PERMISSION_ACTIONS.DELETE,
      PERMISSION_ACTIONS.SUSPEND,
      PERMISSION_ACTIONS.REINSTATE,
    ],
    [PERMISSION_RESOURCES.DRIVERS]: [
      PERMISSION_ACTIONS.VIEW,
      PERMISSION_ACTIONS.CREATE,
      PERMISSION_ACTIONS.UPDATE,
      PERMISSION_ACTIONS.DELETE,
      PERMISSION_ACTIONS.APPROVE,
      PERMISSION_ACTIONS.REJECT,
      PERMISSION_ACTIONS.SUSPEND,
      PERMISSION_ACTIONS.REINSTATE,
    ],
    [PERMISSION_RESOURCES.PASSENGERS]: [
      PERMISSION_ACTIONS.VIEW,
      PERMISSION_ACTIONS.CREATE,
      PERMISSION_ACTIONS.UPDATE,
      PERMISSION_ACTIONS.DELETE,
      PERMISSION_ACTIONS.SUSPEND,
      PERMISSION_ACTIONS.REINSTATE,
    ],
    [PERMISSION_RESOURCES.TRIPS]: [
      PERMISSION_ACTIONS.VIEW,
      PERMISSION_ACTIONS.UPDATE,
      PERMISSION_ACTIONS.DELETE,
      PERMISSION_ACTIONS.OVERRIDE,
    ],
    [PERMISSION_RESOURCES.PAYMENTS]: [
      PERMISSION_ACTIONS.VIEW,
      PERMISSION_ACTIONS.CREATE,
      PERMISSION_ACTIONS.UPDATE,
      PERMISSION_ACTIONS.REFUND,
    ],
    [PERMISSION_RESOURCES.WALLETS]: [
      PERMISSION_ACTIONS.VIEW,
      PERMISSION_ACTIONS.UPDATE,
      PERMISSION_ACTIONS.CREATE,
      PERMISSION_ACTIONS.DELETE,
    ],
    [PERMISSION_RESOURCES.PAYOUTS]: [
      PERMISSION_ACTIONS.VIEW,
      PERMISSION_ACTIONS.CREATE,
      PERMISSION_ACTIONS.UPDATE,
      PERMISSION_ACTIONS.APPROVE,
      PERMISSION_ACTIONS.REJECT,
    ],
    [PERMISSION_RESOURCES.DISPUTES]: [
      PERMISSION_ACTIONS.VIEW,
      PERMISSION_ACTIONS.CREATE,
      PERMISSION_ACTIONS.UPDATE,
      PERMISSION_ACTIONS.DELETE,
    ],
    [PERMISSION_RESOURCES.NOTIFICATIONS]: [
      PERMISSION_ACTIONS.VIEW,
      PERMISSION_ACTIONS.CREATE,
      PERMISSION_ACTIONS.UPDATE,
      PERMISSION_ACTIONS.DELETE,
    ],
    [PERMISSION_RESOURCES.SYSTEM_SETTINGS]: [
      PERMISSION_ACTIONS.VIEW,
      PERMISSION_ACTIONS.UPDATE,
      PERMISSION_ACTIONS.CONFIGURE,
    ],
    [PERMISSION_RESOURCES.ADMIN_USERS]: [
      PERMISSION_ACTIONS.VIEW,
      PERMISSION_ACTIONS.CREATE,
      PERMISSION_ACTIONS.UPDATE,
      PERMISSION_ACTIONS.DELETE,
      PERMISSION_ACTIONS.SUSPEND,
      PERMISSION_ACTIONS.REINSTATE,
    ],
    [PERMISSION_RESOURCES.AUDIT_LOGS]: [
      PERMISSION_ACTIONS.VIEW,
      PERMISSION_ACTIONS.EXPORT,
    ],
    [PERMISSION_RESOURCES.ANALYTICS]: [
      PERMISSION_ACTIONS.VIEW,
      PERMISSION_ACTIONS.EXPORT,
    ],
    [PERMISSION_RESOURCES.REPORTS]: [
      PERMISSION_ACTIONS.VIEW,
      PERMISSION_ACTIONS.CREATE,
      PERMISSION_ACTIONS.EXPORT,
    ],
  },
  [ADMIN_ROLES.OPERATIONS_ADMIN]: {
    [PERMISSION_RESOURCES.USERS]: [
      PERMISSION_ACTIONS.VIEW,
    ],
    [PERMISSION_RESOURCES.DRIVERS]: [
      PERMISSION_ACTIONS.VIEW,
    ],
    [PERMISSION_RESOURCES.PASSENGERS]: [
      PERMISSION_ACTIONS.VIEW,
    ],
    [PERMISSION_RESOURCES.TRIPS]: [
      PERMISSION_ACTIONS.VIEW,
      PERMISSION_ACTIONS.OVERRIDE,
    ],
    [PERMISSION_RESOURCES.PAYMENTS]: [
      PERMISSION_ACTIONS.VIEW,
    ],
    [PERMISSION_RESOURCES.NOTIFICATIONS]: [
      PERMISSION_ACTIONS.VIEW,
    ],
    [PERMISSION_RESOURCES.ANALYTICS]: [
      PERMISSION_ACTIONS.VIEW,
    ],
  },
  [ADMIN_ROLES.FINANCE_ADMIN]: {
    [PERMISSION_RESOURCES.PAYMENTS]: [
      PERMISSION_ACTIONS.VIEW,
      PERMISSION_ACTIONS.REFUND,
    ],
    [PERMISSION_RESOURCES.WALLETS]: [
      PERMISSION_ACTIONS.VIEW,
    ],
    [PERMISSION_RESOURCES.PAYOUTS]: [
      PERMISSION_ACTIONS.VIEW,
      PERMISSION_ACTIONS.APPROVE,
      PERMISSION_ACTIONS.REJECT,
    ],
    [PERMISSION_RESOURCES.ANALYTICS]: [
      PERMISSION_ACTIONS.VIEW,
      PERMISSION_ACTIONS.EXPORT,
    ],
    [PERMISSION_RESOURCES.REPORTS]: [
      PERMISSION_ACTIONS.VIEW,
      PERMISSION_ACTIONS.EXPORT,
    ],
  },
  [ADMIN_ROLES.COMPLIANCE_ADMIN]: {
    [PERMISSION_RESOURCES.DRIVERS]: [
      PERMISSION_ACTIONS.VIEW,
      PERMISSION_ACTIONS.APPROVE,
      PERMISSION_ACTIONS.REJECT,
      PERMISSION_ACTIONS.SUSPEND,
      PERMISSION_ACTIONS.REINSTATE,
    ],
    [PERMISSION_RESOURCES.PASSENGERS]: [
      PERMISSION_ACTIONS.VIEW,
      PERMISSION_ACTIONS.SUSPEND,
      PERMISSION_ACTIONS.REINSTATE,
    ],
    [PERMISSION_RESOURCES.DISPUTES]: [
      PERMISSION_ACTIONS.VIEW,
      PERMISSION_ACTIONS.UPDATE,
    ],
    [PERMISSION_RESOURCES.AUDIT_LOGS]: [
      PERMISSION_ACTIONS.VIEW,
    ],
  },
  [ADMIN_ROLES.SUPPORT_ADMIN]: {
    [PERMISSION_RESOURCES.USERS]: [
      PERMISSION_ACTIONS.VIEW,
    ],
    [PERMISSION_RESOURCES.DRIVERS]: [
      PERMISSION_ACTIONS.VIEW,
    ],
    [PERMISSION_RESOURCES.PASSENGERS]: [
      PERMISSION_ACTIONS.VIEW,
    ],
    [PERMISSION_RESOURCES.TRIPS]: [
      PERMISSION_ACTIONS.VIEW,
    ],
    [PERMISSION_RESOURCES.DISPUTES]: [
      PERMISSION_ACTIONS.VIEW,
      PERMISSION_ACTIONS.CREATE,
      PERMISSION_ACTIONS.UPDATE,
    ],
    [PERMISSION_RESOURCES.NOTIFICATIONS]: [
      PERMISSION_ACTIONS.VIEW,
      PERMISSION_ACTIONS.CREATE,
    ],
  },
  [ADMIN_ROLES.VIEW_ONLY]: {
    [PERMISSION_RESOURCES.USERS]: [
      PERMISSION_ACTIONS.VIEW,
    ],
    [PERMISSION_RESOURCES.DRIVERS]: [
      PERMISSION_ACTIONS.VIEW,
    ],
    [PERMISSION_RESOURCES.PASSENGERS]: [
      PERMISSION_ACTIONS.VIEW,
    ],
    [PERMISSION_RESOURCES.TRIPS]: [
      PERMISSION_ACTIONS.VIEW,
    ],
    [PERMISSION_RESOURCES.ANALYTICS]: [
      PERMISSION_ACTIONS.VIEW,
    ],
  },
};

// Check if admin has permission for resource + action
export const hasPermission = (adminRole, resource, action) => {
  if (!adminRole || !PERMISSION_MATRIX[adminRole]) {
    return false;
  }
  
  const rolePermissions = PERMISSION_MATRIX[adminRole];
  if (!rolePermissions[resource]) {
    return false;
  }
  
  return rolePermissions[resource].includes(action);
};

// Get all resources an admin can access
export const getAccessibleResources = (adminRole) => {
  if (!adminRole || !PERMISSION_MATRIX[adminRole]) {
    return [];
  }
  
  return Object.keys(PERMISSION_MATRIX[adminRole]);
};

// Get all actions for a resource
export const getAllowedActions = (adminRole, resource) => {
  if (!adminRole || !PERMISSION_MATRIX[adminRole]) {
    return [];
  }
  
  return PERMISSION_MATRIX[adminRole][resource] || [];
};

// Check if admin can view a specific page/module
export const canViewModule = (adminRole, module) => {
  const moduleToResource = {
    'operations': PERMISSION_RESOURCES.TRIPS,
    'accounts': PERMISSION_RESOURCES.USERS,
    'finance': PERMISSION_RESOURCES.PAYMENTS,
    'system': PERMISSION_RESOURCES.SYSTEM_SETTINGS,
    'analytics': PERMISSION_RESOURCES.ANALYTICS,
    'communication': PERMISSION_RESOURCES.NOTIFICATIONS,
    'admin-management': PERMISSION_RESOURCES.ADMIN_USERS,
  };
  
  const resource = moduleToResource[module];
  if (!resource) return false;
  
  return hasPermission(adminRole, resource, PERMISSION_ACTIONS.VIEW);
};

// Export the matrix for reference
export { PERMISSION_MATRIX };